export enum RequestStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  REVIEW = "REVIEW",
  REVIEWED = "REVIEWED",
  APPROVED = "APPROVED",
  DECLINED = "DECLINED",

  CATEGORIZED = "CATEGORIZED",
  POSTED = "POSTED",
  BIDDING = "BIDDING",
  AWARDED = "AWARDED",

  POREVIEW = "PO REVIEW",
  POREVIEWED = "PO REVIEWED",
  POAPPROVED = "PO APPROVED",
  PODECLINED = "PO DECLINED",

  INSPECTION = "INSPECTION",
  PARTIAL = "PARTIAL",
  FULFILLED = "FULFILLED",
  UNFULFILLED = "UNFULFILLED",
  CANCELLED = "CANCELLED",
  LATE = "LATE",
}

export enum RequestStatusAction {
  FULFILL = "FULFILL",
  UNFULFILL = "UNFULFILL",
  CANCEL = "CANCEL",
  LATE = "LATE",
  PRINT = "PRINT",
}
