name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm ci

      - name: Update REACT_APP_BUILD_VERSION
        run: |
          currentDate=$(date +'%Y%m%d')
          currentVersion=$(grep -oP '^REACT_APP_BUILD_VERSION=\K.*' .env)
          if [ -z "$currentVersion" ]; then
            newVersion="${currentDate}.1"
          else
            currentYearMonthDay="${currentVersion:0:8}"
            currentIncrement="${currentVersion:9}"
            if [ "$currentYearMonthDay" -eq "$currentDate" ]; then
              newIncrement=$((currentIncrement + 1))
            else
              newIncrement=1
            fi
            newVersion="${currentDate}.${newIncrement}"
          fi
          sed -i "s/^REACT_APP_BUILD_VERSION=.*$/REACT_APP_BUILD_VERSION=${newVersion}/" .env

      - name: Update .env with new version and REACT_APP_API_URL
        run: |
          sed -i 's/^REACT_APP_API_URL=.*/REACT_APP_API_URL=dev-gso1/' .env

      - name: Build
        run: npm run build # The build command of your project
        env:
          CI: false

      - name: Copy .htaccess files
        run: cp -r .htaccess build/

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: build # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
